version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/build/

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu # codedeploy에서 ec2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다
    group: ubuntu